image: archlinux/base


stages:
    - format
    - builds
    - tests


format:
    stage: format
    before_script:
    - pacman -Sy --noconfirm
    - pacman -S rust diffutils gawk grep --noconfirm
    script:
    - for i in $( du -a . | awk '{print $2}' | grep -i ".rs$" ); do
    - cp $i temp.txt
    - rustfmt $i
    - cmp $i temp.txt
    - done


rust-monkey-interpreter-build:
    stage: builds
    before_script:
        - pacman -Sy --noconfirm
        - pacman -S base-devel libffi rust --noconfirm
    script:
        - cargo build


rust-monkey-interpreter-tests:
    stage: tests
    before_script:
        - pacman -Sy --noconfirm
        - pacman -S base-devel libffi rust --noconfirm
    script:
        - cargo test
