image: archlinux/base


stages:
    - format
    - builds
    - tests
    - tagging

format:
    stage: format
    before_script:
    - pacman -Sy --noconfirm
    - pacman -S rust diffutils gawk grep --noconfirm
    script:
    - for i in $( du -a ./src/ | awk '{print $2}' | grep -i "[.]rs$" ); do
    - echo $i
    - cp $i temp.txt
    - rustfmt $i
    - cmp $i temp.txt
    - done


rust-monkey-interpreter-build:
    stage: builds
    before_script:
        - pacman -Sy --noconfirm
        - pacman -S base-devel libffi rust --noconfirm
    script:
        - cargo build


rust-monkey-interpreter-tests:
    stage: tests
    before_script:
        - pacman -Sy --noconfirm
        - pacman -S base-devel libffi rust --noconfirm
    script:
        - cargo test


rust-monkey-interpreter-version-tagging:
    stage: tagging
    before_script:
        - pacman -Sy --noconfirm
        - pacman -S base-devel git openssh --noconfirm
    script:
        # Get version.
        - VERSION=`cat Cargo.toml | grep '^version = ' | cut -d '"' -f 2`
        # Setup ability to push.
        - eval $(ssh-agent -s)
        - mkdir -p $HOME/.ssh/
        - touch $HOME/.ssh/known_hosts
        - ssh-keyscan -t rsa gitlab.com >> $HOME/.ssh/known_hosts
        - echo "$GITLAB_CI_AUTO_TAG_KEY" | tr -d '\r' | ssh-add - > /dev/null
        # Test if tag already exists.
        - export VERSION_TAG_EXISTS=$(git tag | grep $VERSION | wc -l)
        - test $VERSION_TAG_EXISTS -eq 1 && exit 0
        # Create tag and push it.
        - git tag $VERSION
        - git push origin $VERSION
    only:
        - master
