name: Git History

on: pull_request

env:
  # Forcing Earthly to use colours, to make reading output easier.
  FORCE_COLOR: 1

jobs:
  clean:
    name: Clean
    runs-on: ubuntu-latest
    steps:
      - name: Download Earthly.
        uses: earthly/actions-setup@6e152169bdc2c3c53fe75d763863d260ac9b1f82 # v1.0.12
        with:
          version: v0.8.15
      - name: Checkout code.
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
      - name: Check clean Git history.
        run: earthly --ci +check-clean-git-history --from_reference "origin/${{ github.base_ref }}"
