name: Continuous Delivery (CD)

on:
  push:
    branches:
      - main

# https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@3f4784dbc19347947972489b7ed79193ff704b10 # v4.1.2
        with:
          token: ${{ secrets.MY_RELEASE_PLEASE_TOKEN }}
